# Generated by Django 2.2.7 on 2020-06-03 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 8, 54, 54, 733403)),
        ),
    ]
