# Generated by Django 2.2.7 on 2020-07-05 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 8, 1, 34, 816892)),
        ),
    ]
