# Generated by Django 2.2.7 on 2020-07-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200705_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentProduct',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
