# Generated by Django 2.2.7 on 2019-11-09 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191109_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproduct',
            name='payment',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 7, 33, 41, 453969)),
        ),
    ]
