# Generated by Django 2.2.7 on 2019-11-09 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191109_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(to='api.Product'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 7, 37, 32, 833382)),
        ),
    ]
