# Generated by Django 2.2.7 on 2019-11-09 01:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191109_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.Product'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 7, 39, 30, 388224)),
        ),
    ]
