# Generated by Django 2.2.7 on 2019-11-09 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191109_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(to='api.PaymentProduct'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 7, 42, 59, 223652)),
        ),
    ]
