# Generated by Django 2.2.7 on 2019-11-30 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191109_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 24, 32, 164157)),
        ),
    ]
