# Generated by Django 2.2.7 on 2021-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=64, verbose_name=(('Одноразовая тренировка', 'Одноразовая тренировка'), ('Тренировки с тренером', 'Тренировки с тренером'), ('Неделя с тренером', 'Неделя с тренером'), ('Самостоятельные тренировки', 'Самостоятельные тренировки')))),
                ('price', models.IntegerField()),
                ('description_1', models.CharField(max_length=64)),
                ('description_2', models.CharField(max_length=64)),
                ('description_3', models.CharField(max_length=64)),
                ('description_4', models.CharField(max_length=64)),
                ('description_5', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
    ]
