# Generated by Django 2.2.7 on 2020-11-07 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 11, 23, 32, 996289)),
        ),
    ]
