# Generated by Django 2.2.7 on 2021-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='training_type',
            field=models.CharField(choices=[('Одноразовая тренировка', 'Одноразовая тренировка'), ('Тренировки с тренером', 'Тренировки с тренером'), ('Неделя с тренером', 'Неделя с тренером'), ('Самостоятельные тренировки', 'Самостоятельные тренировки')], max_length=64),
        ),
    ]
