# Generated by Django 2.2.7 on 2020-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201107_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='visits',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
